
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    /// <summary>
    /// 羽毛球球路最小验证表
    /// </summary>
    private badminton.TbShuttlecockShotTest m_TbShuttlecockShotTest;
    public badminton.TbShuttlecockShotTest TbShuttlecockShotTest 
    {
        get
        {
            if (m_TbShuttlecockShotTest == null)
            {
                m_TbShuttlecockShotTest = new badminton.TbShuttlecockShotTest(defaultLoader("badminton_tbshuttlecockshottest"));
                m_TbShuttlecockShotTest.ResolveRef(this);
            }
            return m_TbShuttlecockShotTest;
        }
        set
        {
            m_TbShuttlecockShotTest = value;
            m_TbShuttlecockShotTest.ResolveRef(this);
        }
    }
    /// <summary>
    /// ??????????
    /// </summary>
    private badminton.TbShuttlecockShot m_TbShuttlecockShot;
    public badminton.TbShuttlecockShot TbShuttlecockShot 
    {
        get
        {
            if (m_TbShuttlecockShot == null)
            {
                m_TbShuttlecockShot = new badminton.TbShuttlecockShot(defaultLoader("badminton_tbshuttlecockshot"));
                m_TbShuttlecockShot.ResolveRef(this);
            }
            return m_TbShuttlecockShot;
        }
        set
        {
            m_TbShuttlecockShot = value;
            m_TbShuttlecockShot.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    public void Reload()
    {
        m_TbItem = null;
        m_TbShuttlecockShotTest = null;
        m_TbShuttlecockShot = null;
    }

    //public partial void Init();

    public void Init(){}
}

}
