
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.badminton
{
public sealed partial class ShuttlecockShot : Luban.BeanBase
{
    public ShuttlecockShot(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        HorizontalSpeed = _buf.ReadFloat();
        LaunchAngle = _buf.ReadFloat();
        Drag = _buf.ReadFloat();
        Description = _buf.ReadString();
    }

    public static ShuttlecockShot DeserializeShuttlecockShot(ByteBuf _buf)
    {
        return new badminton.ShuttlecockShot(_buf);
    }

    /// <summary>
    /// ??
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// ????
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// ??????m/s?
    /// </summary>
    public readonly float HorizontalSpeed;
    /// <summary>
    /// ???????
    /// </summary>
    public readonly float LaunchAngle;
    /// <summary>
    /// ????
    /// </summary>
    public readonly float Drag;
    /// <summary>
    /// ??
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -596503905;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "horizontalSpeed:" + HorizontalSpeed + ","
        + "launchAngle:" + LaunchAngle + ","
        + "drag:" + Drag + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

