
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.badminton
{
public sealed partial class ShuttlecockShotTest : Luban.BeanBase
{
    public ShuttlecockShotTest(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        HorizontalSpeed = _buf.ReadFloat();
        LaunchAngle = _buf.ReadFloat();
        Drag = _buf.ReadFloat();
        Description = _buf.ReadString();
    }

    public static ShuttlecockShotTest DeserializeShuttlecockShotTest(ByteBuf _buf)
    {
        return new badminton.ShuttlecockShotTest(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 球路名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 水平初速度（m/s）
    /// </summary>
    public readonly float HorizontalSpeed;
    /// <summary>
    /// 发射仰角（度）
    /// </summary>
    public readonly float LaunchAngle;
    /// <summary>
    /// 阻力系数
    /// </summary>
    public readonly float Drag;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 1510040529;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "horizontalSpeed:" + HorizontalSpeed + ","
        + "launchAngle:" + LaunchAngle + ","
        + "drag:" + Drag + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

