
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.badminton
{
/// <summary>
/// ??????????
/// </summary>
public partial class TbShuttlecockShot
{
    private readonly System.Collections.Generic.Dictionary<int, badminton.ShuttlecockShot> _dataMap;
    private readonly System.Collections.Generic.List<badminton.ShuttlecockShot> _dataList;
    
    public TbShuttlecockShot(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, badminton.ShuttlecockShot>(n);
        _dataList = new System.Collections.Generic.List<badminton.ShuttlecockShot>(n);
        for(int i = n ; i > 0 ; --i)
        {
            badminton.ShuttlecockShot _v;
            _v = global::GameConfig.badminton.ShuttlecockShot.DeserializeShuttlecockShot(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, badminton.ShuttlecockShot> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<badminton.ShuttlecockShot> DataList => _dataList;

    public badminton.ShuttlecockShot GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public badminton.ShuttlecockShot Get(int key) => _dataMap[key];
    public badminton.ShuttlecockShot this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

