
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.badminton
{
/// <summary>
/// 羽毛球球路最小验证表
/// </summary>
public partial class TbShuttlecockShotTest
{
    private readonly System.Collections.Generic.Dictionary<int, badminton.ShuttlecockShotTest> _dataMap;
    private readonly System.Collections.Generic.List<badminton.ShuttlecockShotTest> _dataList;
    
    public TbShuttlecockShotTest(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, badminton.ShuttlecockShotTest>(n);
        _dataList = new System.Collections.Generic.List<badminton.ShuttlecockShotTest>(n);
        for(int i = n ; i > 0 ; --i)
        {
            badminton.ShuttlecockShotTest _v;
            _v = global::GameConfig.badminton.ShuttlecockShotTest.DeserializeShuttlecockShotTest(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, badminton.ShuttlecockShotTest> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<badminton.ShuttlecockShotTest> DataList => _dataList;

    public badminton.ShuttlecockShotTest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public badminton.ShuttlecockShotTest Get(int key) => _dataMap[key];
    public badminton.ShuttlecockShotTest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

